import { DMMF } from "@prisma/generator-helper";
import { generateEnum } from "./generateEnum";
import { generateModel } from "./generateModel";
import { InternalGeneratorOptions } from "./onGenerate";

export const generateTypes = (
  datamodel: DMMF.Datamodel,
  config: InternalGeneratorOptions
) => {
  let file = `// This file was generated by a custom prisma generator, do not edit manually.\n`;

  const models = datamodel.models;

  for (const model of models) {
    file += generateModel(model, config);
  }

  const enums = datamodel.enums;
  for (const enumItem of enums) {
    file += generateEnum(enumItem, config);
  }

  return file;
};
